MOBILE_NO_XPATH = '//*[@id="TfMOBILENO"]'
LOGIN_BUTTON_XPATH = '//*[@id="btRtoLogin"]'
PASSWORD_XPATH = '//*[@id="tfPASSWORD"]'
CAPTCHA_IMG_XPATH = '//*[@id="vahancaptcha:CaptchaID"]'
CAPTCHA_BOX_XPATH = '//*[@id="vahancaptcha:ref_captcha"]'
CAPTCHA_INPUT_XPATH = '//*[@id="vahancaptcha:CaptchaID"]'
EMPTY_XPATH = '//html'
RC_STATUS_LOGIN_XPATH = '//*[@id="searchstatusfrm"]//div[contains(text(),"RC Status")]'
REGISTRATION_NO_TEXTBOX_XPATH = '//*[@id="regn_no1_exact"]'
VAHAN_SEARCH_BUTTON_XPATH = '//*[@type="submit"]//span[contains(text(),"Vahan Search")]'
RC_STATUS_SEARCH_PAGE_XPATH = '//h1[contains(text(),"RC Status")]'

DUPLICATE_DATA_CHECK = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[11]/div[1]'

REGISTRATION_NO_XPATH = '//div[@title="Registration Number"]'
VEHICLE_CLASS_XPATH = '//div[@title="Vehicle Class"]'
FUEL_XPATH = '//div[@title="Fuel"]'
MODEL_XPATH = '//span[@title="Model Name"]'
MANUFACTURER_XPATH = '//span[@title="Manufacturer Name"]'
REGISTERING_AUTHORITY_XPATH = '//span[@title="Registering Authority"]'
RC_STATUS_XPATH = '//div[@title="RC Status"]/span'

OWNER_NAME = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[2]/div[2]'
REGISTRATION_DATE = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[2]/div[4]'
FITNESS_REGN = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[4]/div[2]/span'
PUCC = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[5]/div[2]/span'
MV_TAX = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[4]/div[4]'
INSURANCE_COMPANY = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[7]/span[1]'
INSURANCE_POLICY = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[7]/span[3]'
INSURANCE_VALIDITY = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[7]/span[2]'
PERMIT_NO = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[11]/div[2]'
PERMIT_VALID = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[11]/div[4]/span'
NP_AUTH_NO = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[18]/div[2]'
NP_AUTH_UP_TO = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[18]/div[4]/span'
FINANCED = '/html/body/form/div/div[3]/div[3]/div[1]/div/div/div/div[19]/div/span'

SEARCH_PAGE_URL = 'https://vahan.parivahan.gov.in/nrservices/faces/user/citizen/searchstatus.xhtml'